baseURL = "https://www.simonebellavia.com/"
title = "Simone Bellavia"
theme ="basic"
languageCode = "en-us"
enableEmoji = true 
copyright = "Â© 2021-22 made by <a href='https://twitter.com/simoneb1x'>@simoneb1x</a>."
description = "Simone Bellavia. Business & Integration Arch Analyst at Accenture. Passionate MSc Data Science student at UniTn."

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  titleEmoji = ":rocket:"
  twitter = "simoneb1x"

[Permalinks]
  post = "post/:slug"

[[params.menu]]
  name = "blog"
  url = "post/"

[[params.menu]]
  name = "post series"
  url = "series/"
  

[[params.menu]]
  name = "about"
  url = "about/"
  

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true