baseURL = "http://sibellavia.github.io"
languageCode = "en-us"
title = "Simone Bellavia's Web Page"
disableKinds = ["taxonomy",]

[markup.highlight]
  codeFences = true         # Enable highlighting for ``` blocks
  guessSyntax = true        # Try to guess syntax if not specified
  style = "monokai"         # Use the monokai theme
  noClasses = false         # Use CSS classes (recommended)
  # lineNos = true          # Uncomment to add line numbers