baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Blog'
pageRef = '/blog'
weight = 20


[[permalinks]]
blog = "/blog/:year/:month/:day/:title/"

[[params]]
mainSections = ["blog"]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
