name: Zoe - Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write        # This is needed for deploying to Pages
      id-token: write     # This is needed for Pages authentication
      contents: write      # This is needed for pushing to gh-pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0

      - name: Download and Install Zoe
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git clone https://${GH_TOKEN}@github.com/sibellavia/zoe-experimenting.git
          cd zoe-experimenting
          zig build
          # Add the built binary to PATH
          echo "${PWD}/zig-out/bin" >> $GITHUB_PATH
          cd ..

      - name: Build site
        run: |
          zoe build
          ls -la public
        
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 